"""Federation trust constants."""
LOCAL_PEER = "__local__"
KNOWN_UNVERIFIED = "KNOWN_UNVERIFIED"
DIRECT_ONLY = "DIRECT_ONLY"
RECOMMENDATION_ONLY = "RECOMMENDATION_ONLY"
TRANSITIVE = "TRANSITIVE"
TRUST_LEVELS = {"NONE", "LOW", "NORMAL", "HIGH"}
VERIFY = {"KNOWN_UNVERIFIED", "VERIFIED_ONE_WAY", "VERIFIED_MUTUAL", "VERIFIED_IN_PERSON", "VERIFIED_ADMIN"}
PROPAGATION = {DIRECT_ONLY, RECOMMENDATION_ONLY, TRANSITIVE}
