"""Safe, optional document previews generated by the isolated index worker."""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from PIL import Image, ImageOps


CACHE_DIR = ".webcache"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".tif", ".tiff", ".bmp", ".avif", ".heic", ".heif"}
OFFICE_SUFFIXES = {".doc", ".docx", ".odt", ".rtf", ".xls", ".xlsx", ".ods", ".ppt", ".pptx", ".odp"}
VIDEO_SUFFIXES = {".mp4", ".mkv", ".mov", ".avi", ".webm"}
SUPPORTED_SUFFIXES = IMAGE_SUFFIXES | OFFICE_SUFFIXES | VIDEO_SUFFIXES | {".pdf"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def detect_preview_tools() -> dict[str, Any]:
    """Detect commands without executing them, so startup stays fast and safe."""
    commands = {
        "imagemagick": shutil.which("magick") or shutil.which("convert"),
        "pdftoppm": shutil.which("pdftoppm"),
        "libreoffice": shutil.which("libreoffice") or shutil.which("soffice"),
        "ffmpeg": shutil.which("ffmpeg"),
    }
    return {
        "detected_at": utc_now(),
        "commands": {name: bool(path) for name, path in commands.items()},
        "paths": commands,
        "pillow": True,
        "supported": {
            "images": True,
            "pdf": bool(commands["pdftoppm"]),
            "office": bool(commands["libreoffice"] and commands["pdftoppm"]),
            "video": bool(commands["ffmpeg"]),
        },
    }


class PreviewService:
    """Create immutable previews below a private cache, never beside originals."""

    def __init__(self, root: str | Path, tools: dict[str, Any] | None = None):
        self.root = Path(root).expanduser().resolve()
        self.cache = self.root / CACHE_DIR
        self.tools = tools or detect_preview_tools()
        self.timeout = self._bounded_env("SIMPLEOFFICE_PREVIEW_TIMEOUT_SECONDS", 45, 5, 300)
        self.max_bytes = self._bounded_env("SIMPLEOFFICE_PREVIEW_MAX_BYTES", 256 * 1024 * 1024, 1024, 2 * 1024 * 1024 * 1024)
        self.max_pixels = self._bounded_env("SIMPLEOFFICE_PREVIEW_MAX_PIXELS", 80_000_000, 1_000_000, 250_000_000)

    @staticmethod
    def _bounded_env(name: str, default: int, minimum: int, maximum: int) -> int:
        try:
            value = int(os.environ.get(name, str(default)))
        except ValueError:
            value = default
        return max(minimum, min(maximum, value))

    def supports(self, path: Path) -> bool:
        return os.environ.get("SIMPLEOFFICE_PREVIEWS", "1").strip().lower() not in {"0", "false", "off"} and path.suffix.lower() in SUPPORTED_SUFFIXES

    def generate(self, path: Path, metadata: dict[str, Any]) -> dict[str, Any]:
        path = path.resolve(strict=True)
        path.relative_to(self.root)
        suffix = path.suffix.lower()
        digest = str(metadata.get("sha256", ""))
        document_id = str(metadata.get("document_id", ""))
        if not self.supports(path) or not digest or not document_id or path.is_symlink():
            return {"status": "unsupported", "source_sha256": digest}
        if path.stat().st_size > self.max_bytes:
            return {"status": "skipped_limit", "source_sha256": digest}

        destination = self.cache / document_id / digest
        thumbnail = destination / "thumbnail.webp"
        collage = destination / "collage.webp"
        if thumbnail.is_file() and not thumbnail.is_symlink():
            return self._result(digest, thumbnail, collage if collage.is_file() else None, "cache")

        destination.parent.mkdir(parents=True, exist_ok=True)
        try:
            with tempfile.TemporaryDirectory(prefix="preview-", dir=destination.parent) as temporary_name:
                temporary = Path(temporary_name)
                converter = self._convert(path, suffix, temporary)
                generated_thumbnail = temporary / "thumbnail.webp"
                if not generated_thumbnail.is_file():
                    return {"status": "unsupported", "source_sha256": digest}
                destination.mkdir(parents=True, exist_ok=True)
                generated_thumbnail.replace(thumbnail)
                generated_collage = temporary / "collage.webp"
                if generated_collage.is_file():
                    generated_collage.replace(collage)
                self._prune(document_id, digest)
                return self._result(digest, thumbnail, collage if collage.is_file() else None, converter)
        except (OSError, ValueError, subprocess.SubprocessError, Image.DecompressionBombError):
            return {"status": "failed", "source_sha256": digest, "error": "conversion_failed"}

    def _convert(self, source: Path, suffix: str, temporary: Path) -> str:
        if suffix in IMAGE_SUFFIXES:
            try:
                self._thumbnail(source, temporary / "thumbnail.webp")
                return "pillow"
            except (OSError, ValueError):
                imagemagick = self.tools["paths"].get("imagemagick")
                if not imagemagick:
                    raise
                self._run([imagemagick, str(source), "-auto-orient", "-thumbnail", "1200x1200>", "-quality", "82", str(temporary / "thumbnail.webp")])
                return "imagemagick"
        if suffix == ".pdf":
            return self._pdf(source, temporary)
        if suffix in OFFICE_SUFFIXES:
            office = self.tools["paths"].get("libreoffice")
            if not office:
                return "unavailable"
            self._run([office, "--headless", "--convert-to", "pdf", "--outdir", str(temporary), "--", str(source)])
            pdfs = list(temporary.glob("*.pdf"))
            return "libreoffice+" + self._pdf(pdfs[0], temporary) if pdfs else "unavailable"
        if suffix in VIDEO_SUFFIXES:
            ffmpeg = self.tools["paths"].get("ffmpeg")
            if not ffmpeg:
                return "unavailable"
            frame = temporary / "frame.png"
            self._run([ffmpeg, "-nostdin", "-v", "error", "-ss", "1", "-i", str(source), "-frames:v", "1", "-vf", "scale=1200:-2", "-y", str(frame)])
            if frame.is_file():
                self._thumbnail(frame, temporary / "thumbnail.webp")
                return "ffmpeg+pillow"
        return "unavailable"

    def _pdf(self, source: Path, temporary: Path) -> str:
        pdftoppm = self.tools["paths"].get("pdftoppm")
        if not pdftoppm:
            return "unavailable"
        prefix = temporary / "page"
        self._run([pdftoppm, "-f", "1", "-l", "4", "-scale-to", "1200", "-png", "--", str(source), str(prefix)])
        pages = sorted(temporary.glob("page-*.png"))[:4]
        if not pages:
            return "unavailable"
        self._thumbnail(pages[0], temporary / "thumbnail.webp")
        if len(pages) > 1:
            self._collage(pages, temporary / "collage.webp")
        return "pdftoppm+pillow"

    def _thumbnail(self, source: Path, destination: Path) -> None:
        Image.MAX_IMAGE_PIXELS = self.max_pixels
        with Image.open(source) as opened:
            image = ImageOps.exif_transpose(opened).convert("RGB")
            image.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
            image.save(destination, "WEBP", quality=82, method=4)

    def _collage(self, pages: list[Path], destination: Path) -> None:
        opened = []
        try:
            for page in pages:
                image = Image.open(page).convert("RGB")
                image.thumbnail((580, 760), Image.Resampling.LANCZOS)
                opened.append(image.copy())
            width = 1200
            height = max(1, ((len(opened) + 1) // 2) * 780)
            canvas = Image.new("RGB", (width, height), "#e9ecef")
            for index, image in enumerate(opened):
                x, y = (index % 2) * 600 + 10, (index // 2) * 780 + 10
                canvas.paste(image, (x, y))
            canvas.save(destination, "WEBP", quality=78, method=4)
        finally:
            for image in opened:
                image.close()

    def _run(self, command: list[str]) -> None:
        result = subprocess.run(command, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, timeout=self.timeout, check=False, env={**os.environ, "HOME": str(self.cache)})
        if result.returncode != 0:
            raise subprocess.SubprocessError("converter returned a non-zero status")

    def _result(self, digest: str, thumbnail: Path, collage: Path | None, converter: str) -> dict[str, Any]:
        result = {"status": "ready", "source_sha256": digest, "generated_at": utc_now(), "converter": converter, "thumbnail": str(thumbnail.relative_to(self.root))}
        if collage:
            result["collage"] = str(collage.relative_to(self.root))
        return result

    def _prune(self, document_id: str, current_digest: str) -> None:
        root = self.cache / document_id
        for entry in root.iterdir():
            if entry.name != current_digest and entry.is_dir() and not entry.is_symlink():
                shutil.rmtree(entry, ignore_errors=True)

    def cached_path(self, metadata: dict[str, Any], variant: str = "thumbnail") -> Path | None:
        preview = metadata.get("preview", {})
        if preview.get("status") != "ready" or preview.get("source_sha256") != metadata.get("sha256"):
            return None
        relative = str(preview.get(variant, ""))
        if not relative:
            return None
        candidate = self.root / relative
        try:
            candidate.resolve(strict=True).relative_to(self.cache.resolve())
        except (OSError, ValueError):
            return None
        return candidate if candidate.is_file() and not candidate.is_symlink() else None
