"""Inventory of persistent application stores relevant to S3 coverage.

Every value names either a user-facing S3 provider, an admin-only provider,
or an explicit exclusion reason. Keep the architectural test in
``tests/test_s3_overlay_coverage.py`` in sync when a store is added.
"""

PERSISTENCE_COVERAGE = {
    # User data currently projected by the overlay.
    "calendar_store": "provider:calendar",
    "contact_store": "provider:contacts",
    "document_store": "provider:documents",
    "document_store_part_1": "provider:documents-index",
    "mail_client": "provider:mail",
    "object_store": "provider:objects",
    "project_store": "provider:projects",
    "todo_store": "provider:tasks",
    "business_document_generation": "provider:invoices",
    # User data requiring a separate, explicitly permissioned projection.
    "customer_credit": "admin-provider:financial credit ledger requires a dedicated role",
    "euer_store": "admin-provider:tax records require a dedicated finance role",
    "eur_store": "admin-provider:receipt data requires a dedicated finance role",
    "finance_store": "admin-provider:financial records require a dedicated finance role",
    "finance_schema": "excluded:finance table schema is internal implementation detail",
    "form_store": "admin-provider:form records can contain arbitrary submitted personal data",
    "personnel": "admin-provider:employee schedules and absence notes are sensitive",
    "personnel_time_clock": "admin-provider:employee punch records are sensitive",
    "personnel_time_insights": "admin-provider:aggregated personnel data is sensitive",
    "rental_store": "admin-provider:tenancy and property records are sensitive",
    "rental_billing": "admin-provider:tenant billing is financial data",
    "rental_calc": "admin-provider:tenant cost allocation is financial data",
    "shopping_store": "admin-provider:shopping records have no S3 authorization model",
    "inventory": "admin-provider:inventory enrichment has no principal-aware read API",
    "contact_extensions": "admin-provider:CRM extensions use contact-scoped permissions",
    # Federation payload/state is withheld until each resource has an explicit
    # trust and directional visibility policy. Secrets are never exportable.
    "federation_store": "excluded:transfer state and peer payloads are not a user-facing read model",
    "federation_trust_store": "excluded:trust decisions require a dedicated audited projection",
    "federation_attestations": "excluded:attestation internals are not user-facing data",
    "federation_blocks": "excluded:transport block state is operational and not a domain export",
    "federation_catalog": "excluded:remote catalogs require peer trust filtering",
    "federation_directory_store": "excluded:directory data requires discovery consent filtering",
    "federation_mail": "excluded:federated mail may contain remote private content",
    "federation_rendezvous_store": "excluded:rendezvous state contains endpoint and nonce data",
    "federation_peer_schema": "excluded:peer protocol schemas are internal implementation state",
    "v2.federation_policy": "excluded:federation policies contain private sharing configuration",
    # Auth, credentials, keys, encrypted payloads and recovery material.
    "android_auth": "excluded:authentication factors and device secrets",
    "db": "excluded:account hashes, session state and authorization records",
    "password_vault": "excluded:encrypted password vault payloads and unlock material",
    "s3_overlay.credentials": "excluded:encrypted S3 signing secrets",
    "service_credentials": "excluded:service/API credentials",
    "license_master_store": "excluded:cross-installation license credentials and customer state",
    "license_metering": "excluded:license enforcement and usage accounting internals",
    "linux_users": "excluded:operating-system account links and password metadata",
    "v2.authorization": "excluded:authorization grants are internal security state",
    "v2.blob_store": "excluded:physical storage catalog is not a user-facing read model",
    "v2.catalog": "excluded:storage catalog internals",
    "v2.encrypted_blob_store": "excluded:encrypted blob and key metadata",
    "v2.encrypted_recovery_fragments": "excluded:encrypted recovery fragments and key material",
    "v2.master_keys": "excluded:master encryption key profiles",
    "v2.jobs": "excluded:internal storage processing jobs and recovery state",
    "v2.vault_payload_store": "excluded:encrypted vault payloads",
    "v2.overlay": "excluded:storage overlay migration state",
    # Operational state, device control, caches and internal services.
    "audio_output_store": "excluded:local audio device and announcement state",
    "audio_receiver_store": "excluded:local audio receiver configuration",
    "chat_features": "excluded:chat feature flags are operational configuration",
    "chat_status": "excluded:service health and delivery state",
    "chat_store": "admin-provider:chat messages require participant and attachment authorization",
    "datalogger_store": "admin-provider:telemetry requires source-level access control",
    "fritzbox_contacts": "excluded:router sync credentials and unreviewed imported data",
    "gamification_organization": "excluded:organization scoring configuration",
    "gamification_rewards": "excluded:reward policy configuration",
    "gamification_store": "admin-provider:participant privacy requires a dedicated role",
    "google_drive_schema": "excluded:connector state may contain OAuth references",
    "host_automation": "excluded:host command and automation configuration",
    "itip": "excluded:calendar invitation processing state",
    "library.object_care": "admin-provider:physical library records lack principal-aware access",
    "library.store": "admin-provider:library patron data is private",
    "mail_index": "excluded:internal mail search index; EML archive provider is authoritative",
    "osm_address_storage": "excluded:public geodata index, not application-owned user data",
    "printershare_store": "excluded:printer credentials and job control state",
    "project_tracker": "admin-provider:project time and billing records need project ACLs",
    "remote_hub_store": "excluded:remote administration endpoint state",
    "replication_store": "excluded:replication targets and synchronization configuration",
    "settings_store": "excluded:settings include private operational configuration",
    "setup_store": "excluded:installation state and bootstrap configuration",
    "software_artifact_config": "excluded:distribution signing and source configuration",
    "software_artifacts": "excluded:software artifacts have no user-domain ACL model",
    "software_distribution_core": "excluded:software distribution and deployment state",
    "system_management": "excluded:host storage roles and management state",
    "telephony_numbering": "admin-provider:phone number inventory has restricted access",
    "telephony_profiles": "excluded:telephony profile configuration",
}
